[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "viewgeom"                      # PyPI package name users will install
version = "0.1.0"
description = "Fast, lightweight vector viewer for .shp, .geojson, .gpkg, and (geo)parquet with a simple Qt UI."
readme = "README.md"
requires-python = ">=3.9"
license = { text = "MIT" }
authors = [{ name = "Keiko Nomura" }]

# Core deps to make everything work out of the box (no Fiona required)
dependencies = [
  "geopandas>=0.13",
  "shapely>=2.0",
  "pyarrow>=12",     # (geo)parquet
  "pyogrio>=0.7",    # GeoPackage + fast I/O (no Fiona)
  "pandas>=2.0",
  "numpy>=1.23",
  "matplotlib>=3.7",
  "PySide6>=6.5"
]

[project.scripts]
viewgeom = "viewgeom:main"

[project.urls]
Homepage = "https://github.com/nkeikon/geomviewer"
Source   = "https://github.com/nkeikon/geomviewer"
Issues   = "https://github.com/nkeikon/geomviewer/issues"

[tool.hatch.build.targets.wheel]
packages = ["src/viewgeom"]